import { useMemo, useState } from "react";
import { BODY_REGIONS } from "../lib/medicalMapping.js";

/**
 * BodyMap — holographic anatomical human figure.
 *
 * Renders a hand-built SVG anatomy chart (silhouette + organs + anterior
 * muscles + nervous system) in the app's ember hologram style. Body regions
 * flagged by medicalMapping.analyzeHealth() light up with severity-coded
 * pulsing hotspots and callout labels; clicking one opens a detail panel
 * listing the conditions, medicines and interactions behind it.
 *
 * Pure SVG + CSS animation — no WebGL, cheap to render anywhere.
 */

/* ── geometry helpers ─────────────────────────────────────────────────── */

/** Catmull-Rom → cubic bezier, closed loop. Keeps hand-tuned points smooth. */
function smoothClosedPath(pts) {
  const n = pts.length;
  const p = (i) => pts[(i + n) % n];
  let d = `M ${p(0)[0].toFixed(1)} ${p(0)[1].toFixed(1)} `;
  for (let i = 0; i < n; i++) {
    const p0 = p(i - 1), p1 = p(i), p2 = p(i + 1), p3 = p(i + 2);
    const c1x = p1[0] + (p2[0] - p0[0]) / 6;
    const c1y = p1[1] + (p2[1] - p0[1]) / 6;
    const c2x = p2[0] - (p3[0] - p1[0]) / 6;
    const c2y = p2[1] - (p3[1] - p1[1]) / 6;
    d += `C ${c1x.toFixed(1)} ${c1y.toFixed(1)}, ${c2x.toFixed(1)} ${c2y.toFixed(1)}, ${p2[0].toFixed(1)} ${p2[1].toFixed(1)} `;
  }
  return d + "Z";
}

/* Viewer-left half of the body outline (A-pose, front view, 420×920 box).
   The right half is generated by mirroring around x = 210. */
const HALF_OUTLINE = [
  [210, 26],  [186, 34],  [173, 58],  [172, 84],  [179, 106], [190, 122],
  [195, 134], [193, 152], [186, 163], [162, 178], [132, 194], [116, 212],
  [110, 240], [106, 282], [100, 330], [95, 372],  [89, 425],  [86, 458],
  [76, 492],  [78, 530],  [86, 550],  [98, 542],  [104, 505], [108, 468],
  [115, 425], [122, 372], [128, 330], [136, 288], [147, 254], [153, 262],
  [158, 300], [164, 342], [162, 378], [152, 412], [149, 448], [152, 490],
  [160, 545], [166, 600], [167, 645], [162, 690], [166, 728], [162, 775],
  [168, 820], [172, 842], [166, 860], [172, 872], [193, 876], [199, 868],
  [198, 844], [195, 800], [193, 745], [194, 695], [196, 655], [195, 600],
  [196, 550], [200, 505],
];

const BODY_PATH = (() => {
  const left = HALF_OUTLINE;
  const right = left
    .slice(1) // skip crown (shared apex)
    .reverse()
    .map(([x, y]) => [420 - x, y]);
  // loop: crown → left side → crotch(210,480 approx via last pts) → right side → crown
  return smoothClosedPath([...left, [210, 480], ...right]);
})();

const SEV_ORDER = { severe: 0, moderate: 1, mild: 2 };

/* ── tiny building blocks ─────────────────────────────────────────────── */

function Mirrored({ children }) {
  return (
    <>
      <g>{children}</g>
      <g transform="translate(420,0) scale(-1,1)">{children}</g>
    </>
  );
}

function SevBadge({ severity }) {
  return <span className={`bm-sev-badge bm-sev-${severity}`}>{severity}</span>;
}

/* ── anatomy layers (drawn once, styled in CSS) ───────────────────────── */

function OrgansLayer({ affected, selected }) {
  const cls = (regionId, base) => {
    const f = affected[regionId];
    let c = `bm-organ ${base}`;
    if (f) c += ` bm-affected bm-a-${f.severity}`;
    if (selected === regionId) c += " bm-organ-selected";
    return c;
  };

  return (
    <g className="bm-layer bm-layer-organs">
      {/* Brain — two hemispheres + gyri */}
      <g id="org-brain" className={cls("brain", "bm-org-brain")}>
        <path d="M210,50 C196,48 184,54 181,66 C178,78 182,92 192,97 C198,100 206,100 210,97 C214,100 222,100 228,97 C238,92 242,78 239,66 C236,54 224,48 210,50 Z" />
        <path className="bm-gyri" d="M210,52 L210,96 M195,60 C201,66 199,76 193,82 M188,70 C194,72 196,80 192,88 M225,60 C219,66 221,76 227,82 M232,70 C226,72 224,80 228,88" />
      </g>
      {/* Eyes */}
      <g id="org-eyes" className={cls("eyes", "bm-org-eyes")}>
        <circle cx="195" cy="97" r="4.5" />
        <circle cx="225" cy="97" r="4.5" />
        <circle cx="195" cy="97" r="1.8" className="bm-pupil" />
        <circle cx="225" cy="97" r="1.8" className="bm-pupil" />
      </g>
      {/* Trachea + throat */}
      <g id="org-throat" className={cls("ent", "bm-org-throat")}>
        <path d="M206,138 L206,228 M214,138 L214,228" />
        <path className="bm-rings" d="M205,150 L215,150 M205,162 L215,162 M205,186 L215,186 M205,200 L215,200 M205,214 L215,214" />
      </g>
      {/* Thyroid — butterfly */}
      <g id="org-thyroid" className={cls("thyroid", "bm-org-thyroid")}>
        <path d="M206,164 C200,160 194,162 193,169 C192,176 196,181 203,180 C206,179 207,175 206,171 Z" />
        <path d="M214,164 C220,160 226,162 227,169 C228,176 224,181 217,180 C214,179 213,175 214,171 Z" />
        <path d="M206,170 L214,170" />
      </g>
      {/* Lungs */}
      <g id="org-lung-l" className={cls("lungs", "bm-org-lung")}>
        <path d="M202,232 C188,226 170,236 163,258 C156,282 155,310 160,326 C164,338 182,340 196,332 C202,328 204,318 204,300 L204,244 C204,238 204,234 202,232 Z" />
        <path className="bm-fissure" d="M162,286 C174,280 192,280 203,286 M166,308 C178,302 192,302 203,306" />
      </g>
      <g id="org-lung-r" className={cls("lungs", "bm-org-lung")}>
        <path d="M218,232 C232,226 250,236 257,258 C264,282 265,310 260,326 C256,338 240,340 228,330 C222,325 218,310 217,296 L216,244 C216,238 216,234 218,232 Z" />
        <path className="bm-fissure" d="M258,290 C246,284 228,284 217,290" />
      </g>
      {/* Heart — apex to viewer-right (patient left) */}
      <g id="org-heart" className={cls("heart", "bm-org-heart")}>
        <path d="M215,250 C208,244 198,247 196,256 C194,264 199,274 208,282 C216,290 228,300 234,306 C240,298 246,286 247,274 C248,262 242,252 233,250 C226,249 219,252 215,258 Z" />
        <path className="bm-vessel" d="M214,250 C212,242 214,236 220,232 M222,250 C222,242 226,236 232,234" />
      </g>
      {/* Liver — viewer-left wedge */}
      <g id="org-liver" className={cls("liver", "bm-org-liver")}>
        <path d="M160,336 C176,328 202,330 214,336 C216,344 214,352 206,360 C194,372 178,380 170,378 C162,375 157,360 158,348 Z" />
      </g>
      {/* Stomach — J curve viewer-right */}
      <g id="org-stomach" className={cls("stomach", "bm-org-stomach")}>
        <path d="M216,330 C228,328 244,336 250,350 C256,364 252,378 242,384 C234,389 226,388 222,382 C218,376 222,370 228,368 C236,365 240,358 236,350 C232,342 222,340 216,342 Z" />
      </g>
      {/* Pancreas — behind stomach */}
      <g id="org-pancreas" className={cls("pancreas", "bm-org-pancreas")}>
        <path d="M196,388 C192,382 194,376 200,375 C214,373 232,370 244,372 C248,373 248,378 244,379 C230,381 212,384 204,389 C201,391 197,391 196,388 Z" />
      </g>
      {/* Kidneys — beans, hilum inward */}
      <g id="org-kidney-l" className={cls("kidneys", "bm-org-kidney")}>
        <path d="M176,388 C168,390 164,398 165,408 C166,418 172,424 179,422 C184,420 186,414 184,410 C182,407 182,403 184,400 C186,395 182,389 176,388 Z" />
      </g>
      <g id="org-kidney-r" className={cls("kidneys", "bm-org-kidney")}>
        <path d="M244,386 C252,388 256,396 255,406 C254,416 248,422 241,420 C236,418 234,412 236,408 C238,405 238,401 236,398 C234,393 238,387 244,386 Z" />
      </g>
      {/* Intestines — colon frame + small bowel coils */}
      <g id="org-intestines" className={cls("intestines", "bm-org-intestines")}>
        <path d="M176,468 L176,404 C176,398 180,394 186,393 L234,391 C240,391 244,395 244,400 L244,466 C244,474 238,480 230,482 L222,484" />
        <path className="bm-coils" d="M186,412 C196,406 208,406 216,412 C224,418 232,416 236,410 M184,430 C194,424 206,426 212,432 C220,439 230,436 236,430 M186,448 C196,442 208,444 214,450 C222,457 230,454 236,448 M190,464 C200,458 212,460 218,466 C224,471 230,470 234,466" />
      </g>
      {/* Bladder */}
      <g id="org-bladder" className={cls("bladder", "bm-org-bladder")}>
        <path d="M197,496 C197,488 223,488 223,496 C223,506 216,512 210,512 C204,512 197,506 197,496 Z" />
      </g>
      {/* Knee joints */}
      <g id="org-knee-l" className={cls("joints", "bm-org-knee")}>
        <circle cx="180" cy="660" r="9" />
        <path d="M174,652 A9,9 0 0 1 186,652" className="bm-joint-cap" />
      </g>
      <g id="org-knee-r" className={cls("joints", "bm-org-knee")}>
        <circle cx="240" cy="660" r="9" />
        <path d="M234,652 A9,9 0 0 1 246,652" className="bm-joint-cap" />
      </g>
    </g>
  );
}

function MusclesLayer() {
  return (
    <g className="bm-layer bm-layer-muscles">
      <Mirrored>
        {/* sternocleidomastoid */}
        <path className="bm-muscle" d="M203,132 C200,142 194,152 188,160 C191,162 195,162 197,159 C201,151 205,141 207,133 Z" />
        {/* trapezius */}
        <path className="bm-muscle" d="M188,162 C176,168 156,178 138,190 C152,192 168,190 180,184 C185,180 188,170 188,162 Z" />
        {/* deltoid */}
        <path className="bm-muscle" d="M136,192 C124,196 114,208 111,224 C109,238 112,250 118,254 C126,250 133,240 137,228 C141,216 141,200 136,192 Z" />
        <path className="bm-stria" d="M130,200 C124,210 120,224 119,240 M137,204 C131,214 127,228 126,244" />
        {/* pectoralis major */}
        <path className="bm-muscle" d="M208,204 C186,202 160,210 146,232 C144,244 152,258 168,264 C184,270 200,268 207,262 C209,244 209,222 208,204 Z" />
        <path className="bm-stria" d="M205,214 C186,214 164,222 152,238 M206,230 C190,230 172,236 160,250 M206,246 C194,246 180,250 170,258" />
        {/* biceps */}
        <path className="bm-muscle" d="M132,262 C124,272 118,292 116,312 C115,326 118,336 124,338 C130,334 134,320 136,304 C138,288 137,272 132,262 Z" />
        {/* forearm flexors */}
        <path className="bm-muscle" d="M118,344 C110,360 103,388 99,416 C97,432 99,446 104,450 C110,444 114,428 116,410 C119,388 120,362 118,344 Z" />
        {/* serratus digitations */}
        <path className="bm-stria" d="M156,272 C162,274 166,278 168,282 M154,286 C160,288 164,292 166,296 M154,300 C160,302 164,306 166,310" />
        {/* obliques */}
        <path className="bm-muscle" d="M166,306 C160,322 158,344 160,364 C162,378 168,388 176,390 C180,376 180,354 178,336 C176,322 172,310 166,306 Z" />
        {/* rectus abdominis (half column) */}
        <g className="bm-abs">
          <rect className="bm-muscle" x="186" y="290" width="20" height="20" rx="6" />
          <rect className="bm-muscle" x="186" y="313" width="20" height="20" rx="6" />
          <rect className="bm-muscle" x="186" y="336" width="20" height="20" rx="6" />
          <rect className="bm-muscle" x="186" y="359" width="20" height="26" rx="7" />
        </g>
        {/* sartorius ribbon */}
        <path className="bm-muscle bm-thin" d="M162,470 C172,500 186,540 194,580 C198,600 199,622 197,640 L192,638 C193,618 191,598 187,582 C180,546 167,506 157,478 Z" />
        {/* quadriceps */}
        <path className="bm-muscle" d="M158,486 C152,516 152,556 156,592 C159,616 164,634 170,640 C176,632 179,612 179,588 C179,552 174,512 166,488 C163,482 160,482 158,486 Z" />
        <path className="bm-muscle" d="M182,500 C178,530 178,566 181,598 C183,616 187,630 191,636 C195,628 196,610 196,590 C196,558 192,522 187,500 C185,494 183,494 182,500 Z" />
        <path className="bm-stria" d="M164,510 C161,540 161,576 165,608 M186,516 C184,544 184,576 187,604" />
        {/* patellar tendon */}
        <path className="bm-stria" d="M178,644 C178,652 178,660 179,668" />
        {/* tibialis anterior */}
        <path className="bm-muscle bm-thin" d="M172,684 C168,712 167,748 170,784 C172,806 176,824 180,830 C183,822 184,802 183,778 C182,744 179,708 176,686 Z" />
        {/* gastrocnemius (medial head visible) */}
        <path className="bm-muscle" d="M190,690 C186,712 185,742 188,768 C190,782 193,792 196,794 C198,786 199,768 198,748 C197,724 194,702 190,690 Z" />
      </Mirrored>
    </g>
  );
}

function NervesLayer() {
  return (
    <g className="bm-layer bm-layer-nerves">
      {/* spinal cord + vertebrae ticks */}
      <path className="bm-nerve bm-nerve-cord" d="M210,104 L210,470" />
      <path className="bm-vertebrae" d="M204,152 L216,152 M204,168 L216,168 M204,184 L216,184 M204,200 L216,200 M204,216 L216,216 M204,232 L216,232 M204,248 L216,248 M204,264 L216,264 M204,280 L216,280 M204,296 L216,296 M204,312 L216,312 M204,328 L216,328 M204,344 L216,344 M204,360 L216,360 M204,376 L216,376 M204,392 L216,392 M204,408 L216,408 M204,424 L216,424 M204,440 L216,440 M204,456 L216,456" />
      <Mirrored>
        {/* facial branches */}
        <path className="bm-nerve bm-thin" d="M210,92 C202,92 196,98 192,104 M210,100 C204,104 198,110 194,116" />
        {/* brachial plexus → arm (median, ulnar, radial) */}
        <path className="bm-nerve" d="M210,176 C192,182 168,192 150,208 C138,220 128,244 124,268" />
        <path className="bm-nerve" d="M150,208 C136,232 126,272 121,312 C117,344 112,390 108,428 C105,452 100,486 94,516" />
        <path className="bm-nerve bm-thin" d="M148,214 C130,244 121,290 117,330 C113,368 108,414 103,452 C101,470 97,494 92,514" />
        <path className="bm-nerve bm-thin" d="M124,268 C119,296 116,330 113,366 C110,398 106,438 101,474" />
        {/* intercostal fans */}
        <path className="bm-nerve bm-thin" d="M210,232 C196,234 182,240 172,248 M210,254 C196,257 183,263 173,272 M210,276 C197,280 185,286 176,294 M210,298 C198,302 187,308 179,316" />
        {/* lumbar plexus → femoral */}
        <path className="bm-nerve" d="M210,400 C198,412 184,432 176,456 C169,480 166,516 168,552 C170,588 174,620 178,646" />
        {/* sciatic → tibial + common peroneal */}
        <path className="bm-nerve" d="M210,436 C202,452 194,478 190,506 C186,534 185,572 186,606 C187,630 188,648 190,662" />
        <path className="bm-nerve bm-thin" d="M190,662 C186,690 181,726 179,762 C177,794 178,824 180,846" />
        <path className="bm-nerve bm-thin" d="M190,662 C192,694 193,732 193,768 C193,800 194,828 196,850" />
        {/* plexus nodes */}
        <circle className="bm-nerve-node" cx="150" cy="208" r="2.4" />
        <circle className="bm-nerve-node" cx="176" cy="456" r="2.4" />
        <circle className="bm-nerve-node" cx="190" cy="662" r="2.2" />
      </Mirrored>
      <circle className="bm-nerve-node" cx="210" cy="176" r="2.8" />
      <circle className="bm-nerve-node" cx="210" cy="400" r="2.8" />
    </g>
  );
}

/* ── figure decorations ───────────────────────────────────────────────── */

function Backdrop() {
  return (
    <g className="bm-backdrop" aria-hidden="true">
      <rect x="0" y="0" width="420" height="920" fill="url(#bm-grid)" className="bm-grid-rect" />
      {/* side ruler */}
      <g className="bm-ruler">
        {Array.from({ length: 19 }, (_, i) => (
          <line key={i} x1={i % 2 ? 410 : 405} y1={40 + i * 46} x2="416" y2={40 + i * 46} />
        ))}
      </g>
      {/* aura behind figure */}
      <ellipse cx="210" cy="440" rx="150" ry="340" fill="url(#bm-aura)" />
    </g>
  );
}

function Pedestal() {
  return (
    <g className="bm-pedestal" aria-hidden="true">
      <ellipse cx="210" cy="878" rx="140" ry="24" fill="url(#bm-floor)" />
      <ellipse className="bm-ring bm-ring-1" cx="210" cy="878" rx="118" ry="19" />
      <ellipse className="bm-ring bm-ring-2" cx="210" cy="878" rx="88" ry="14" />
      <ellipse className="bm-ring bm-ring-3" cx="210" cy="878" rx="52" ry="8" />
    </g>
  );
}

function ScanLine() {
  return (
    <g className="bm-scan" aria-hidden="true">
      <rect x="30" y="-60" width="360" height="52" fill="url(#bm-scanfill)" />
      <line x1="30" y1="-8" x2="390" y2="-8" className="bm-scan-edge" />
    </g>
  );
}

/* ── hotspots + callouts ──────────────────────────────────────────────── */

function Callouts({ findings, selected, onSelect }) {
  // assign label slots per side, ordered by anchor height
  const bySide = { L: [], R: [] };
  for (const f of findings) bySide[f.regionDef.side || "R"].push(f);
  const slots = [];
  for (const side of ["L", "R"]) {
    const list = bySide[side].sort((a, b) => a.regionDef.anchor[1] - b.regionDef.anchor[1]);
    list.forEach((f, i) => {
      const y = Math.min(120 + i * 58, 820);
      slots.push({ f, side, labelY: y });
    });
  }

  return (
    <g className="bm-callouts">
      {slots.map(({ f, side, labelY }) => {
        const [ax, ay] = f.regionDef.anchor;
        const chipW = 92;
        const chipX = side === "L" ? 4 : 420 - chipW - 4;
        const innerX = side === "L" ? chipX + chipW : chipX;
        const isSel = selected === f.region;
        return (
          <g
            key={f.region}
            className={`bm-hotspot bm-sev-${f.severity}${isSel ? " bm-selected" : ""}`}
            onClick={() => onSelect(isSel ? null : f.region)}
            role="button"
            tabIndex={0}
            onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); onSelect(isSel ? null : f.region); } }}
            aria-label={`${f.regionDef.label} — ${f.severity}`}
          >
            <polyline
              className="bm-leader"
              points={`${ax},${ay} ${innerX + (side === "L" ? 14 : -14)},${labelY} ${innerX},${labelY}`}
            />
            {/* label chip */}
            <g className="bm-chip" transform={`translate(${chipX}, ${labelY - 15})`}>
              <rect width={chipW} height="30" rx="9" />
              <circle cx="13" cy="15" r="3.5" className="bm-chip-dot" />
              <text x="24" y="19">{f.regionDef.short}</text>
            </g>
            {/* anchor marker */}
            <circle className="bm-spot-ring" cx={ax} cy={ay} r="11" />
            <circle className="bm-spot-ring bm-spot-ring2" cx={ax} cy={ay} r="11" />
            <circle className="bm-spot-core" cx={ax} cy={ay} r="4" />
            <circle className="bm-spot-hit" cx={ax} cy={ay} r="17" />
          </g>
        );
      })}
    </g>
  );
}

/* ── side panel ───────────────────────────────────────────────────────── */

function DetailPanel({ finding, onBack }) {
  const d = finding.regionDef;
  return (
    <div className={`bm-detail bm-border-${finding.severity}`}>
      <button type="button" className="bm-back" onClick={onBack}>← All regions</button>
      <div className="bm-detail-head">
        <h3>{d.label}</h3>
        <SevBadge severity={finding.severity} />
      </div>
      <p className="bm-detail-blurb">{d.blurb}</p>

      {finding.conditions.length > 0 && (
        <div className="bm-detail-block">
          <span className="bm-detail-label">Detected conditions</span>
          <div className="bm-cond-chips">
            {finding.conditions.map((c) => (
              <span key={c.name} className={`bm-cond-chip cond-${c.status}`}>
                {c.name}
                {c.status !== "unknown" && <em>{c.status}</em>}
              </span>
            ))}
          </div>
        </div>
      )}

      {finding.medicines.length > 0 && (
        <div className="bm-detail-block">
          <span className="bm-detail-label">Acting medicines · {finding.medicines.length}</span>
          <ul className="bm-med-list">
            {finding.medicines.map((m) => (
              <li key={m.name}>
                <div className="bm-med-line">
                  <strong>{m.name}</strong>
                  {m.dose && <span className="bm-med-chip">{m.dose}</span>}
                  {m.frequency && <span className="bm-med-chip">{m.frequency}</span>}
                </div>
                <span className="bm-med-purpose">{m.purpose}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {finding.interactions.length > 0 && (
        <div className="bm-detail-block">
          <span className="bm-detail-label bm-detail-label-warn">⚠ Drug interactions here</span>
          {finding.interactions.map((ix, i) => (
            <div key={i} className={`bm-ix bm-border-${ix.severity}`}>
              <div className="bm-ix-meds">{(ix.medicines || []).join(" + ")}</div>
              <p>{ix.description}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function FindingsList({ findings, onSelect }) {
  return (
    <div className="bm-findings">
      {findings.map((f) => (
        <button
          type="button"
          key={f.region}
          className={`bm-finding bm-border-${f.severity}`}
          onClick={() => onSelect(f.region)}
        >
          <div className="bm-finding-top">
            <strong>{f.regionDef.label}</strong>
            <SevBadge severity={f.severity} />
          </div>
          <span className="bm-finding-sub">
            {f.conditions.length > 0 && `${f.conditions.map((c) => c.name).join(", ")} · `}
            {f.medicines.length} medicine{f.medicines.length !== 1 ? "s" : ""}
            {f.interactions.length > 0 && ` · ⚠ ${f.interactions.length} interaction${f.interactions.length !== 1 ? "s" : ""}`}
          </span>
        </button>
      ))}
    </div>
  );
}

/* ── main component ───────────────────────────────────────────────────── */

const LAYERS = [
  { id: "all", label: "All systems" },
  { id: "organs", label: "Organs" },
  { id: "muscles", label: "Muscles" },
  { id: "nerves", label: "Nerves" },
];

export default function BodyMap({ findings = [], meta = null, subtitle }) {
  const [layer, setLayer] = useState("all");
  const [selected, setSelected] = useState(null);

  const sorted = useMemo(
    () => [...findings].sort((a, b) => SEV_ORDER[a.severity] - SEV_ORDER[b.severity]),
    [findings]
  );
  const affected = useMemo(() => {
    const m = {};
    for (const f of sorted) m[f.region] = f;
    return m;
  }, [sorted]);
  const selectedFinding = selected ? affected[selected] : null;
  const clear = sorted.length === 0;

  return (
    <div className="bodymap">
      <div className="bm-stage">
        <div className="bm-stage-head">
          <div>
            <span className="bm-stage-title">
              <span className="bm-live-dot" /> Body systems scan
            </span>
            {subtitle && <span className="bm-stage-sub">{subtitle}</span>}
          </div>
          <div className="bm-layers" role="tablist" aria-label="Anatomy layer">
            {LAYERS.map((l) => (
              <button
                type="button"
                key={l.id}
                role="tab"
                aria-selected={layer === l.id}
                className={`bm-layer-btn${layer === l.id ? " active" : ""}`}
                onClick={() => setLayer(l.id)}
              >
                {l.label}
              </button>
            ))}
          </div>
        </div>

        <div className="bm-svg-wrap">
          <svg
            className="bm-svg"
            data-layer={layer}
            viewBox="0 0 420 920"
            role="img"
            aria-label="Anatomical body map with highlighted health regions"
          >
            <defs>
              <linearGradient id="bm-body-grad" x1="0" y1="0" x2="0" y2="1">
                <stop offset="0" stopColor="#3a1c0c" stopOpacity="0.55" />
                <stop offset="0.5" stopColor="#2a1207" stopOpacity="0.42" />
                <stop offset="1" stopColor="#170a04" stopOpacity="0.5" />
              </linearGradient>
              <linearGradient id="bm-stroke-grad" x1="0" y1="0" x2="0" y2="1">
                <stop offset="0" stopColor="#ffd9a8" />
                <stop offset="0.55" stopColor="#ff8a3d" />
                <stop offset="1" stopColor="#b34a18" />
              </linearGradient>
              <radialGradient id="bm-aura" cx="0.5" cy="0.45" r="0.55">
                <stop offset="0" stopColor="#ff8a3d" stopOpacity="0.10" />
                <stop offset="0.6" stopColor="#e85d1f" stopOpacity="0.045" />
                <stop offset="1" stopColor="#e85d1f" stopOpacity="0" />
              </radialGradient>
              <radialGradient id="bm-floor" cx="0.5" cy="0.5" r="0.5">
                <stop offset="0" stopColor="#ff8a3d" stopOpacity="0.16" />
                <stop offset="0.7" stopColor="#e85d1f" stopOpacity="0.05" />
                <stop offset="1" stopColor="#e85d1f" stopOpacity="0" />
              </radialGradient>
              <linearGradient id="bm-scanfill" x1="0" y1="0" x2="0" y2="1">
                <stop offset="0" stopColor="#ffc978" stopOpacity="0" />
                <stop offset="1" stopColor="#ffc978" stopOpacity="0.13" />
              </linearGradient>
              <linearGradient id="bm-muscle-grad" x1="0" y1="0" x2="1" y2="1">
                <stop offset="0" stopColor="#e85d1f" stopOpacity="0.42" />
                <stop offset="1" stopColor="#8a2f0d" stopOpacity="0.30" />
              </linearGradient>
              <pattern id="bm-grid" width="30" height="30" patternUnits="userSpaceOnUse">
                <path d="M30,0 L0,0 0,30" fill="none" stroke="#ffb066" strokeWidth="0.4" />
              </pattern>
              <filter id="bm-glow" x="-60%" y="-60%" width="220%" height="220%">
                <feGaussianBlur stdDeviation="2.2" result="b" />
                <feMerge>
                  <feMergeNode in="b" />
                  <feMergeNode in="SourceGraphic" />
                </feMerge>
              </filter>
              <filter id="bm-glow-soft" x="-80%" y="-80%" width="260%" height="260%">
                <feGaussianBlur stdDeviation="5" result="b" />
                <feMerge>
                  <feMergeNode in="b" />
                  <feMergeNode in="SourceGraphic" />
                </feMerge>
              </filter>
            </defs>

            <Backdrop />
            <Pedestal />

            <g className="bm-figure">
              {/* silhouette */}
              <path className="bm-body-fill" d={BODY_PATH} />
              <path className="bm-body-stroke" d={BODY_PATH} />
              {/* anatomical landmarks always visible */}
              <g className="bm-landmarks">
                <path d="M183,110 C192,124 198,130 210,132 C222,130 228,124 237,110" />
                <path d="M210,196 C193,192 172,194 152,202 M210,196 C227,192 248,194 268,202" />
                <path d="M172,88 C168,92 168,98 172,102 M248,88 C252,92 252,98 248,102" />
                <circle cx="210" cy="400" r="2.4" className="bm-navel" />
              </g>

              <MusclesLayer />
              <OrgansLayer affected={affected} selected={selected} />
              <NervesLayer />
            </g>

            <ScanLine />

            {/* drifting motes */}
            <g className="bm-motes" aria-hidden="true">
              {[
                [70, 200], [340, 160], [352, 420], [66, 470], [90, 640],
                [335, 610], [130, 120], [300, 750], [110, 790], [318, 280],
              ].map(([x, y], i) => (
                <circle key={i} className="bm-mote" cx={x} cy={y} r={i % 3 === 0 ? 2.2 : 1.4} />
              ))}
            </g>

            <Callouts findings={sorted} selected={selected} onSelect={setSelected} />
          </svg>
        </div>

        <div className="bm-legend">
          <span className="bm-legend-item"><i className="bm-dot bm-dot-mild" /> Mild</span>
          <span className="bm-legend-item"><i className="bm-dot bm-dot-moderate" /> Moderate</span>
          <span className="bm-legend-item"><i className="bm-dot bm-dot-severe" /> Needs attention</span>
        </div>
      </div>

      <aside className="bm-side">
        {meta && (
          <div className="bm-stats">
            <div className="bm-stat">
              <span className="bm-stat-num">{meta.matchedRegions}</span>
              <span className="bm-stat-label">Regions</span>
            </div>
            <div className="bm-stat">
              <span className="bm-stat-num">{meta.medCount}</span>
              <span className="bm-stat-label">Medicines</span>
            </div>
            <div className="bm-stat">
              <span className="bm-stat-num">{meta.conditionCount}</span>
              <span className="bm-stat-label">Conditions</span>
            </div>
            <div className={`bm-stat${meta.interactionCount ? " bm-stat-warn" : ""}`}>
              <span className="bm-stat-num">{meta.interactionCount}</span>
              <span className="bm-stat-label">Interactions</span>
            </div>
          </div>
        )}

        {clear ? (
          <div className="bm-clear">
            <span className="bm-clear-pulse" />
            <h3>Scan clear</h3>
            <p>No prescription activity mapped to any body system yet. Upload a prescription and the scan lights up automatically.</p>
          </div>
        ) : selectedFinding ? (
          <DetailPanel finding={selectedFinding} onBack={() => setSelected(null)} />
        ) : (
          <>
            <p className="bm-hint">Tap a glowing region on the figure — or a card below — to see what's driving it.</p>
            <FindingsList findings={sorted} onSelect={setSelected} />
          </>
        )}

        <p className="bm-disclaimer">
          Mapped automatically from prescription history — an orientation aid, not a diagnosis.
        </p>
      </aside>
    </div>
  );
}
